version: '3.8'

services:
  auth-service2:
    build: ./reviseme-backend/auth2-service
    ports:
      - "5002:5002"  # Expose backend on port 5000
    volumes:
      - ./reviseme-backend/auth2-service:/usr/src/app  # Mount the backend folder
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB  # Connection string for MongoDB
    depends_on:
      - mongo  # Ensure MongoDB starts before this service
    networks:
      - app-network  # Connect to the specified network

  flashcard-service:
    build:
      context: ./reviseme-backend/flashcard-service
    ports:
      - "5001:5001"  # Expose flashcard-service on port 5001
    volumes:
      - ./reviseme-backend/flashcard-service:/usr/src/app  # Mount the backend folder
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB  # Connection string for MongoDB
    depends_on:
      - mongo  # Ensure MongoDB starts before this service
    networks:
      - app-network  # Connect to the specified network

  mongo:
    image: mongo:5.0  # Use the specified MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Use a named volume for persistent data
    networks:
      - app-network  # Connect to the specified network
  
  frontend:
    build:
      context: ./reviseme-frontend # Path to the frontend folder
    ports:
      - "3000:80"
    networks:
      - app-network  # Connect to the specified network

volumes:
  mongo-data:  # Define a named volume for MongoDB data

networks:
  app-network:
    driver: bridge  # Use bridge networking
