services:
  # Frontend (React app)
  frontend:
    build:
      context: ./frontend-auth # Correct path to your React app directory
    ports:
      - "3000:3000" # Expose port 3000 for the React app
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - backend # Wait for the backend to be ready
    volumes:
      - ./frontend-auth:/app # Sync code changes during development

  # Backend (Auth or API service)
  backend:
    build:
      context: ./reviseme-backend/auth-service # Correct path to your backend service
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/reviseme
      - JWT_SECRET=Dinesh0507
    depends_on:
      - mongo
    volumes:
      - ./reviseme-backend/auth-service:/app

  # MongoDB service
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/reviseme